name: Terraform Deployment

trigger:
  branches:
    include:
      - main

jobs:
  - job: TerraformPlan
    displayName: Terraform Plan
    
    steps:
      - script: 'terraform version'
        displayName: 'Terraform Version'

      - script: 'terraform -chdir=Terraform/main/ init -input=false'
        displayName: 'Init'
        env:
          ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
          ARM_TENANT_ID: $(ARM_TENANT_ID)
          ARM_CLIENT_ID: $(ARM_CLIENT_ID)
          ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)

      - script: 'terraform -chdir=main/ validate'
        displayName: 'Validate'

      - script: 'terraform -chdir=Terraform/main/ plan -input=false'
        displayName: 'Plan'
        env:
          ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
          ARM_TENANT_ID: $(ARM_TENANT_ID)
          ARM_CLIENT_ID: $(ARM_CLIENT_ID)
          ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)

  - job: TerraformApply
    displayName: Terraform Apply
  
    steps:
      - script: 'terraform -chdir=Terraform/main/ init -input=false'
        displayName: 'Init'
        env:
          ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
          ARM_TENANT_ID: $(ARM_TENANT_ID)
          ARM_CLIENT_ID: $(ARM_CLIENT_ID)
          ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)

      - script: 'terraform -chdir=Terraform/main/ apply -auto-approve -input=false'
        displayName: 'Apply'
        env:
          ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
          ARM_TENANT_ID: $(ARM_TENANT_ID)
          ARM_CLIENT_ID: $(ARM_CLIENT_ID)
          ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)